version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: diploma_orders
      POSTGRES_USER: ${ORDER_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: